"""create initial schema"""

revision = 'd1a7d4aec64e'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('furniture_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('furniture_type', sa.String(length=50), nullable=True),
    sa.Column('usdc_url', sa.Text(), nullable=True),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key')
    )
    op.create_index('idx_furniture_type', 'furniture_models', ['furniture_type'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confirm_code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('room_shell_usdc_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirm_code')
    )
    op.create_index('idx_rooms_confirm_code', 'rooms', ['confirm_code'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('version_type', sa.String(length=20), nullable=False),
    sa.Column('version_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('s3_json_url', sa.Text(), nullable=True),
    sa.Column('converted_fbx_url', sa.Text(), nullable=True),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("version_type IN ('ORIGINAL', 'OPTIMIZED', 'USER_EDITED')", name='chk_version_type'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'version_no', name='uq_room_id_version_no')
    )
    op.create_table('furniture_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('item_key', sa.String(length=100), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('pos_z', sa.Float(), nullable=False),
    sa.Column('rot_x', sa.Float(), nullable=False),
    sa.Column('rot_y', sa.Float(), nullable=False),
    sa.Column('rot_z', sa.Float(), nullable=False),
    sa.Column('scale_x', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('scale_y', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('scale_z', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('footprint_polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['furniture_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('furniture_items')
    op.drop_table('versions')
    op.drop_index('idx_rooms_confirm_code', table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('idx_furniture_type', table_name='furniture_models')
    op.drop_table('furniture_models')
    # ### end Alembic commands ###
