"""Security helpers for local authentication."""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets


_HASH_NAME = "sha256"
_ITERATIONS = 260_000
_SALT_BYTES = 16


def hash_secret(value: str) -> str:
    """Hash a password or short verification code with PBKDF2."""
    salt = secrets.token_bytes(_SALT_BYTES)
    digest = hashlib.pbkdf2_hmac(_HASH_NAME, value.encode("utf-8"), salt, _ITERATIONS)
    salt_b64 = base64.urlsafe_b64encode(salt).decode("ascii")
    digest_b64 = base64.urlsafe_b64encode(digest).decode("ascii")
    return f"pbkdf2_{_HASH_NAME}${_ITERATIONS}${salt_b64}${digest_b64}"


def verify_secret(value: str, hashed_value: str) -> bool:
    """Return whether value matches a PBKDF2 hash generated by hash_secret."""
    try:
        algorithm, iterations, salt_b64, digest_b64 = hashed_value.split("$", 3)
        if algorithm != f"pbkdf2_{_HASH_NAME}":
            return False
        salt = base64.urlsafe_b64decode(salt_b64.encode("ascii"))
        expected_digest = base64.urlsafe_b64decode(digest_b64.encode("ascii"))
        actual_digest = hashlib.pbkdf2_hmac(
            _HASH_NAME,
            value.encode("utf-8"),
            salt,
            int(iterations),
        )
    except (ValueError, TypeError):
        return False

    return hmac.compare_digest(actual_digest, expected_digest)
