"""Security helpers for authentication."""

from __future__ import annotations

import hashlib
import secrets
from datetime import datetime, timedelta, timezone

from fastapi import HTTPException
from jwt import ExpiredSignatureError, InvalidTokenError, decode, encode
from passlib.context import CryptContext

from server.core.config import settings


pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def hash_secret(value: str) -> str:
    """Hash a password or short verification code."""
    return pwd_context.hash(value)


def verify_secret(value: str, hashed_value: str) -> bool:
    """Return whether value matches a hash generated by hash_secret."""
    if not hashed_value:
        return False
    return pwd_context.verify(value, hashed_value)


def _jwt_secret_key() -> str:
    if not settings.jwt_secret_key:
        raise RuntimeError("JWT_SECRET_KEY is not configured")
    return settings.jwt_secret_key


def create_access_token(subject: str) -> str:
    """Create a signed JWT access token."""
    now = datetime.now(timezone.utc)
    expires_at = now + timedelta(minutes=settings.access_token_expire_minutes)
    payload = {
        "sub": subject,
        "iat": now,
        "exp": expires_at,
    }
    return encode(payload, _jwt_secret_key(), algorithm=settings.jwt_algorithm)


def decode_access_token(token: str) -> dict:
    """Verify a JWT access token and return its payload."""
    try:
        return decode(token, _jwt_secret_key(), algorithms=[settings.jwt_algorithm])
    except ExpiredSignatureError:
        raise HTTPException(status_code=401, detail="인증 토큰이 만료되었습니다.")
    except InvalidTokenError:
        raise HTTPException(status_code=401, detail="유효하지 않은 인증 토큰입니다.")
