"""Update furniture model dimensions from locally converted GLB files."""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from shared.db import SessionLocal  # noqa: E402
from shared.models.furniture_model import FurnitureModel  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default="tmp/roomplan-catalog/manifest.json",
        help="Catalog manifest generated by prepare_roomplan_catalog.py.",
    )
    parser.add_argument(
        "--glb-root",
        default="tmp/roomplan-catalog/glb",
        help="Local root containing converted GLB files.",
    )
    parser.add_argument(
        "--unit-scale",
        type=float,
        default=0.01,
        help="Scale GLB units to meters. RoomPlan catalog GLBs are usually exported in centimeters.",
    )
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def read_glb(path: Path) -> tuple[dict[str, Any], bytes]:
    data = path.read_bytes()
    if len(data) < 20:
        raise ValueError(f"GLB is too small: {path}")

    magic, version, total_length = struct.unpack_from("<III", data, 0)
    if magic != 0x46546C67 or version != 2:
        raise ValueError(f"Unsupported GLB header: {path}")
    if total_length != len(data):
        raise ValueError(f"GLB length mismatch: {path}")

    offset = 12
    json_chunk: bytes | None = None
    bin_chunk = b""
    while offset < len(data):
        chunk_length, chunk_type = struct.unpack_from("<I4s", data, offset)
        offset += 8
        chunk = data[offset : offset + chunk_length]
        offset += chunk_length
        if chunk_type == b"JSON":
            json_chunk = chunk
        elif chunk_type == b"BIN\x00":
            bin_chunk = chunk

    if json_chunk is None:
        raise ValueError(f"GLB missing JSON chunk: {path}")

    return json.loads(json_chunk.decode("utf-8")), bin_chunk


def node_matrix(node: dict[str, Any]) -> np.ndarray:
    if "matrix" in node:
        return np.array(node["matrix"], dtype=float).reshape((4, 4), order="F")

    translation = np.array(node.get("translation", [0.0, 0.0, 0.0]), dtype=float)
    scale = np.array(node.get("scale", [1.0, 1.0, 1.0]), dtype=float)
    rotation = node.get("rotation", [0.0, 0.0, 0.0, 1.0])
    x, y, z, w = [float(value) for value in rotation]

    xx, yy, zz = x * x, y * y, z * z
    xy, xz, yz = x * y, x * z, y * z
    wx, wy, wz = w * x, w * y, w * z
    rotation_matrix = np.array(
        [
            [1.0 - 2.0 * (yy + zz), 2.0 * (xy - wz), 2.0 * (xz + wy), 0.0],
            [2.0 * (xy + wz), 1.0 - 2.0 * (xx + zz), 2.0 * (yz - wx), 0.0],
            [2.0 * (xz - wy), 2.0 * (yz + wx), 1.0 - 2.0 * (xx + yy), 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ],
        dtype=float,
    )

    scale_matrix = np.diag([scale[0], scale[1], scale[2], 1.0])
    translation_matrix = np.identity(4)
    translation_matrix[:3, 3] = translation
    return translation_matrix @ rotation_matrix @ scale_matrix


def transform_bounds(min_values: list[float], max_values: list[float], matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    corners = []
    for x in (min_values[0], max_values[0]):
        for y in (min_values[1], max_values[1]):
            for z in (min_values[2], max_values[2]):
                corners.append([x, y, z, 1.0])
    transformed = (matrix @ np.array(corners, dtype=float).T).T[:, :3]
    return transformed.min(axis=0), transformed.max(axis=0)


def collect_mesh_node_matrices(gltf: dict[str, Any]) -> dict[int, list[np.ndarray]]:
    nodes = gltf.get("nodes", [])
    scene_indices = gltf.get("scenes", [{}])[gltf.get("scene", 0)].get("nodes", [])
    matrices_by_mesh: dict[int, list[np.ndarray]] = {}

    def visit(node_index: int, parent_matrix: np.ndarray) -> None:
        node = nodes[node_index]
        world = parent_matrix @ node_matrix(node)
        if "mesh" in node:
            matrices_by_mesh.setdefault(int(node["mesh"]), []).append(world)
        for child in node.get("children", []):
            visit(int(child), world)

    for node_index in scene_indices:
        visit(int(node_index), np.identity(4))

    if not matrices_by_mesh:
        for index, _mesh in enumerate(gltf.get("meshes", [])):
            matrices_by_mesh[index] = [np.identity(4)]

    return matrices_by_mesh


def glb_dimensions(path: Path) -> tuple[float, float, float]:
    gltf, _bin_chunk = read_glb(path)
    accessors = gltf.get("accessors", [])
    matrices_by_mesh = collect_mesh_node_matrices(gltf)
    mins: list[np.ndarray] = []
    maxs: list[np.ndarray] = []

    for mesh_index, mesh in enumerate(gltf.get("meshes", [])):
        for primitive in mesh.get("primitives", []):
            position_accessor_index = primitive.get("attributes", {}).get("POSITION")
            if position_accessor_index is None:
                continue

            accessor = accessors[int(position_accessor_index)]
            if "min" not in accessor or "max" not in accessor:
                raise ValueError(f"POSITION accessor missing min/max: {path}")

            for matrix in matrices_by_mesh.get(mesh_index, [np.identity(4)]):
                bounds_min, bounds_max = transform_bounds(accessor["min"], accessor["max"], matrix)
                mins.append(bounds_min)
                maxs.append(bounds_max)

    if not mins:
        raise ValueError(f"GLB has no POSITION bounds: {path}")

    overall_min = np.vstack(mins).min(axis=0)
    overall_max = np.vstack(maxs).max(axis=0)
    extents = overall_max - overall_min
    if not all(math.isfinite(float(value)) for value in extents):
        raise ValueError(f"Invalid GLB extents: {path}")

    width = round(float(extents[0]), 6)
    height = round(float(extents[1]), 6)
    depth = round(float(extents[2]), 6)
    return width, depth, height


def local_glb_path(glb_root: Path, glb_key: str) -> Path:
    marker = "/glb/"
    if marker in glb_key:
        return glb_root / glb_key.split(marker, 1)[1]
    return glb_root / glb_key


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest)
    glb_root = Path(args.glb_root)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    items = manifest.get("items", [])

    updates: list[tuple[str, float, float, float]] = []
    failures: list[tuple[str, str]] = []
    for item in items:
        model_key = item["modelKey"]
        path = local_glb_path(glb_root, item["glbKey"])
        try:
            width, depth, height = glb_dimensions(path)
            width = round(width * args.unit_scale, 6)
            depth = round(depth * args.unit_scale, 6)
            height = round(height * args.unit_scale, 6)
        except Exception as exc:
            failures.append((model_key, str(exc)))
            continue
        updates.append((model_key, width, depth, height))

    print(f"Prepared dimension updates: {len(updates)}")
    for model_key, width, depth, height in updates[:10]:
        print(f"  {model_key}: width={width}, depth={depth}, height={height}")
    if len(updates) > 10:
        print(f"  ... {len(updates) - 10} more")

    if failures:
        print(f"Failures: {len(failures)}")
        for model_key, error in failures:
            print(f"  {model_key}: {error}")

    if args.dry_run:
        print("Dry run: database was not updated.")
        return 0 if not failures else 1

    db = SessionLocal()
    try:
        updated = 0
        missing: list[str] = []
        for model_key, width, depth, height in updates:
            model = db.query(FurnitureModel).filter(FurnitureModel.model_key == model_key).first()
            if model is None:
                missing.append(model_key)
                continue
            model.width = width
            model.depth = depth
            model.height = height
            updated += 1
        db.commit()
        print(f"Updated DB rows: {updated}")
        if missing:
            print(f"Missing DB rows: {len(missing)}")
            for model_key in missing:
                print(f"  {model_key}")
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()

    return 0 if not failures else 1


if __name__ == "__main__":
    raise SystemExit(main())
